build_settings:
    ignore:
        - vendor
        - tests

setup:
    composer:
        action: install

test:
    php_unit:
        config:
            - phpunit.xml.dist
        coverage: true

    php_mess_detector:
        allow_failures: true

    php_code_sniffer:
        standard:       PSR2
        encoding:       UTF-8
        allow_failures: true

    php_cpd:
        allow_failures: true

    php_loc:
        allow_failures: true

    php_parallel_lint:
        allow_failures: true

    php_docblock_checker:
        allow_failures: true

    security_checker:
        binary_type:    symfony
        allow_failures: false

complete:
    email_notify:
        default_mailto_address: poisoncorpsee@gmail.com
    telegram_notify:
        auth_token: "%SECRET:telegram_auth_token%"
        recipients:
            - "%SECRET:telegram_chat_id%"
        send_log: false
